# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/bitmessageqt/bitmessageui.ui'
#
# Created: Sun Nov 16 21:19:56 2014
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(885, 580)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/can-icon-24px.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.inbox = QtGui.QWidget()
        self.inbox.setStatusTip(_fromUtf8(""))
        self.inbox.setObjectName(_fromUtf8("inbox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.inbox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayoutSearch = QtGui.QHBoxLayout()
        self.horizontalLayoutSearch.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayoutSearch.setObjectName(_fromUtf8("horizontalLayoutSearch"))
        self.widgetInboxFilters = QtGui.QWidget(self.inbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetInboxFilters.sizePolicy().hasHeightForWidth())
        self.widgetInboxFilters.setSizePolicy(sizePolicy)
        self.widgetInboxFilters.setObjectName(_fromUtf8("widgetInboxFilters"))
        self._2 = QtGui.QHBoxLayout(self.widgetInboxFilters)
        self._2.setMargin(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.inboxSearchLineEdit = QtGui.QLineEdit(self.widgetInboxFilters)
        self.inboxSearchLineEdit.setObjectName(_fromUtf8("inboxSearchLineEdit"))
        self._2.addWidget(self.inboxSearchLineEdit)
        self.inboxSearchOptionCB = QtGui.QComboBox(self.widgetInboxFilters)
        self.inboxSearchOptionCB.setObjectName(_fromUtf8("inboxSearchOptionCB"))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self._2.addWidget(self.inboxSearchOptionCB)
        self.horizontalLayoutSearch.addWidget(self.widgetInboxFilters)
        self.verticalLayout_2.addLayout(self.horizontalLayoutSearch)
        self.splitter = QtGui.QSplitter(self.inbox)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tableWidgetInbox = QtGui.QTableWidget(self.splitter)
        self.tableWidgetInbox.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetInbox.setAlternatingRowColors(True)
        self.tableWidgetInbox.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetInbox.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetInbox.setWordWrap(False)
        self.tableWidgetInbox.setObjectName(_fromUtf8("tableWidgetInbox"))
        self.tableWidgetInbox.setColumnCount(4)
        self.tableWidgetInbox.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(3, item)
        self.tableWidgetInbox.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetInbox.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidgetInbox.horizontalHeader().setHighlightSections(False)
        self.tableWidgetInbox.horizontalHeader().setMinimumSectionSize(27)
        self.tableWidgetInbox.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetInbox.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetInbox.verticalHeader().setVisible(False)
        self.tableWidgetInbox.verticalHeader().setDefaultSectionSize(26)
        self.widgetInboxMessageView = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetInboxMessageView.sizePolicy().hasHeightForWidth())
        self.widgetInboxMessageView.setSizePolicy(sizePolicy)
        self.widgetInboxMessageView.setObjectName(_fromUtf8("widgetInboxMessageView"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widgetInboxMessageView)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widgetInboxSubjectBar = QtGui.QWidget(self.widgetInboxMessageView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetInboxSubjectBar.sizePolicy().hasHeightForWidth())
        self.widgetInboxSubjectBar.setSizePolicy(sizePolicy)
        self.widgetInboxSubjectBar.setMinimumSize(QtCore.QSize(0, 48))
        self.widgetInboxSubjectBar.setMaximumSize(QtCore.QSize(16777215, 256))
        self.widgetInboxSubjectBar.setBaseSize(QtCore.QSize(0, 0))
        self.widgetInboxSubjectBar.setObjectName(_fromUtf8("widgetInboxSubjectBar"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widgetInboxSubjectBar)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.graphicsViewInboxSubjectIcon = QtGui.QGraphicsView(self.widgetInboxSubjectBar)
        self.graphicsViewInboxSubjectIcon.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewInboxSubjectIcon.sizePolicy().hasHeightForWidth())
        self.graphicsViewInboxSubjectIcon.setSizePolicy(sizePolicy)
        self.graphicsViewInboxSubjectIcon.setMinimumSize(QtCore.QSize(48, 48))
        self.graphicsViewInboxSubjectIcon.setMaximumSize(QtCore.QSize(48, 48))
        self.graphicsViewInboxSubjectIcon.setBaseSize(QtCore.QSize(48, 48))
        self.graphicsViewInboxSubjectIcon.setStyleSheet(_fromUtf8("background:rgba(0, 0, 0, 0)"))
        self.graphicsViewInboxSubjectIcon.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsViewInboxSubjectIcon.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewInboxSubjectIcon.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewInboxSubjectIcon.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewInboxSubjectIcon.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewInboxSubjectIcon.setForegroundBrush(brush)
        self.graphicsViewInboxSubjectIcon.setSceneRect(QtCore.QRectF(0.0, 0.0, 48.0, 48.0))
        self.graphicsViewInboxSubjectIcon.setObjectName(_fromUtf8("graphicsViewInboxSubjectIcon"))
        self.horizontalLayout_3.addWidget(self.graphicsViewInboxSubjectIcon)
        self.widget = QtGui.QWidget(self.widgetInboxSubjectBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelInboxSubjectBarSubject = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInboxSubjectBarSubject.sizePolicy().hasHeightForWidth())
        self.labelInboxSubjectBarSubject.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelInboxSubjectBarSubject.setFont(font)
        self.labelInboxSubjectBarSubject.setText(_fromUtf8(""))
        self.labelInboxSubjectBarSubject.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelInboxSubjectBarSubject.setWordWrap(True)
        self.labelInboxSubjectBarSubject.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelInboxSubjectBarSubject.setObjectName(_fromUtf8("labelInboxSubjectBarSubject"))
        self.verticalLayout_4.addWidget(self.labelInboxSubjectBarSubject)
        self.labelInboxSubjectBarFrom = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelInboxSubjectBarFrom.sizePolicy().hasHeightForWidth())
        self.labelInboxSubjectBarFrom.setSizePolicy(sizePolicy)
        self.labelInboxSubjectBarFrom.setText(_fromUtf8(""))
        self.labelInboxSubjectBarFrom.setWordWrap(True)
        self.labelInboxSubjectBarFrom.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelInboxSubjectBarFrom.setObjectName(_fromUtf8("labelInboxSubjectBarFrom"))
        self.verticalLayout_4.addWidget(self.labelInboxSubjectBarFrom)
        self.widget_3 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.graphicsViewInboxSubjectIconTo = QtGui.QGraphicsView(self.widget_3)
        self.graphicsViewInboxSubjectIconTo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewInboxSubjectIconTo.sizePolicy().hasHeightForWidth())
        self.graphicsViewInboxSubjectIconTo.setSizePolicy(sizePolicy)
        self.graphicsViewInboxSubjectIconTo.setMinimumSize(QtCore.QSize(16, 16))
        self.graphicsViewInboxSubjectIconTo.setMaximumSize(QtCore.QSize(16, 16))
        self.graphicsViewInboxSubjectIconTo.setBaseSize(QtCore.QSize(16, 16))
        self.graphicsViewInboxSubjectIconTo.setStyleSheet(_fromUtf8("background:rgba(0, 0, 0, 0)"))
        self.graphicsViewInboxSubjectIconTo.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsViewInboxSubjectIconTo.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewInboxSubjectIconTo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewInboxSubjectIconTo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewInboxSubjectIconTo.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewInboxSubjectIconTo.setForegroundBrush(brush)
        self.graphicsViewInboxSubjectIconTo.setSceneRect(QtCore.QRectF(0.0, 0.0, 16.0, 16.0))
        self.graphicsViewInboxSubjectIconTo.setObjectName(_fromUtf8("graphicsViewInboxSubjectIconTo"))
        self.horizontalLayout_5.addWidget(self.graphicsViewInboxSubjectIconTo)
        self.labelInboxSubjectBarTo = QtGui.QLabel(self.widget_3)
        self.labelInboxSubjectBarTo.setText(_fromUtf8(""))
        self.labelInboxSubjectBarTo.setScaledContents(False)
        self.labelInboxSubjectBarTo.setWordWrap(True)
        self.labelInboxSubjectBarTo.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelInboxSubjectBarTo.setObjectName(_fromUtf8("labelInboxSubjectBarTo"))
        self.horizontalLayout_5.addWidget(self.labelInboxSubjectBarTo)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_3.addWidget(self.widgetInboxSubjectBar)
        self.textEditInboxMessage = QtGui.QTextEdit(self.widgetInboxMessageView)
        self.textEditInboxMessage.setBaseSize(QtCore.QSize(0, 500))
        self.textEditInboxMessage.setReadOnly(True)
        self.textEditInboxMessage.setObjectName(_fromUtf8("textEditInboxMessage"))
        self.verticalLayout_3.addWidget(self.textEditInboxMessage)
        self.verticalLayout_2.addWidget(self.splitter)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/inbox.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.inbox, icon1, _fromUtf8(""))
        self.send = QtGui.QWidget()
        self.send.setObjectName(_fromUtf8("send"))
        self.gridLayout_2 = QtGui.QGridLayout(self.send)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonLoadFromAddressBook = QtGui.QPushButton(self.send)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButtonLoadFromAddressBook.setFont(font)
        self.pushButtonLoadFromAddressBook.setObjectName(_fromUtf8("pushButtonLoadFromAddressBook"))
        self.gridLayout_2.addWidget(self.pushButtonLoadFromAddressBook, 3, 3, 1, 1)
        self.pushButtonFetchNamecoinID = QtGui.QPushButton(self.send)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButtonFetchNamecoinID.setFont(font)
        self.pushButtonFetchNamecoinID.setObjectName(_fromUtf8("pushButtonFetchNamecoinID"))
        self.gridLayout_2.addWidget(self.pushButtonFetchNamecoinID, 3, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.send)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.comboBoxSendFrom = QtGui.QComboBox(self.send)
        self.comboBoxSendFrom.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBoxSendFrom.setObjectName(_fromUtf8("comboBoxSendFrom"))
        self.gridLayout_2.addWidget(self.comboBoxSendFrom, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.send)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.labelFrom = QtGui.QLabel(self.send)
        self.labelFrom.setText(_fromUtf8(""))
        self.labelFrom.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelFrom.setObjectName(_fromUtf8("labelFrom"))
        self.gridLayout_2.addWidget(self.labelFrom, 2, 3, 1, 3)
        self.radioButtonSpecific = QtGui.QRadioButton(self.send)
        self.radioButtonSpecific.setChecked(True)
        self.radioButtonSpecific.setObjectName(_fromUtf8("radioButtonSpecific"))
        self.gridLayout_2.addWidget(self.radioButtonSpecific, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.send)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.send)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.textEditMessage = QtGui.QTextEdit(self.send)
        self.textEditMessage.setObjectName(_fromUtf8("textEditMessage"))
        self.gridLayout_2.addWidget(self.textEditMessage, 5, 1, 2, 6)
        self.radioButtonBroadcast = QtGui.QRadioButton(self.send)
        self.radioButtonBroadcast.setObjectName(_fromUtf8("radioButtonBroadcast"))
        self.gridLayout_2.addWidget(self.radioButtonBroadcast, 1, 1, 1, 4)
        self.lineEditSubject = QtGui.QLineEdit(self.send)
        self.lineEditSubject.setText(_fromUtf8(""))
        self.lineEditSubject.setObjectName(_fromUtf8("lineEditSubject"))
        self.gridLayout_2.addWidget(self.lineEditSubject, 4, 1, 1, 6)
        spacerItem = QtGui.QSpacerItem(20, 297, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.pushButtonSend = QtGui.QPushButton(self.send)
        self.pushButtonSend.setObjectName(_fromUtf8("pushButtonSend"))
        self.gridLayout_2.addWidget(self.pushButtonSend, 7, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 5, 1, 1)
        self.labelSendBroadcastWarning = QtGui.QLabel(self.send)
        self.labelSendBroadcastWarning.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSendBroadcastWarning.sizePolicy().hasHeightForWidth())
        self.labelSendBroadcastWarning.setSizePolicy(sizePolicy)
        self.labelSendBroadcastWarning.setIndent(-1)
        self.labelSendBroadcastWarning.setObjectName(_fromUtf8("labelSendBroadcastWarning"))
        self.gridLayout_2.addWidget(self.labelSendBroadcastWarning, 7, 1, 1, 5)
        self.lineEditTo = QtGui.QComboBox(self.send)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditTo.sizePolicy().hasHeightForWidth())
        self.lineEditTo.setSizePolicy(sizePolicy)
        self.lineEditTo.setEditable(True)
        self.lineEditTo.setObjectName(_fromUtf8("lineEditTo"))
        self.gridLayout_2.addWidget(self.lineEditTo, 3, 1, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/send.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.send, icon2, _fromUtf8(""))
        self.sent = QtGui.QWidget()
        self.sent.setObjectName(_fromUtf8("sent"))
        self.verticalLayout = QtGui.QVBoxLayout(self.sent)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widgetSentFilters = QtGui.QWidget(self.sent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSentFilters.sizePolicy().hasHeightForWidth())
        self.widgetSentFilters.setSizePolicy(sizePolicy)
        self.widgetSentFilters.setObjectName(_fromUtf8("widgetSentFilters"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widgetSentFilters)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.sentSearchLineEdit = QtGui.QLineEdit(self.widgetSentFilters)
        self.sentSearchLineEdit.setObjectName(_fromUtf8("sentSearchLineEdit"))
        self.horizontalLayout_2.addWidget(self.sentSearchLineEdit)
        self.sentSearchOptionCB = QtGui.QComboBox(self.widgetSentFilters)
        self.sentSearchOptionCB.setObjectName(_fromUtf8("sentSearchOptionCB"))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.sentSearchOptionCB)
        self.horizontalLayout.addWidget(self.widgetSentFilters)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter_2 = QtGui.QSplitter(self.sent)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.tableWidgetSent = QtGui.QTableWidget(self.splitter_2)
        self.tableWidgetSent.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetSent.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.tableWidgetSent.setAlternatingRowColors(True)
        self.tableWidgetSent.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetSent.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetSent.setWordWrap(False)
        self.tableWidgetSent.setObjectName(_fromUtf8("tableWidgetSent"))
        self.tableWidgetSent.setColumnCount(4)
        self.tableWidgetSent.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(3, item)
        self.tableWidgetSent.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetSent.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidgetSent.horizontalHeader().setHighlightSections(False)
        self.tableWidgetSent.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetSent.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetSent.verticalHeader().setVisible(False)
        self.tableWidgetSent.verticalHeader().setStretchLastSection(False)
        self.widgetSentMessageView = QtGui.QWidget(self.splitter_2)
        self.widgetSentMessageView.setObjectName(_fromUtf8("widgetSentMessageView"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widgetSentMessageView)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widgetSentSubjectBar = QtGui.QWidget(self.widgetSentMessageView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSentSubjectBar.sizePolicy().hasHeightForWidth())
        self.widgetSentSubjectBar.setSizePolicy(sizePolicy)
        self.widgetSentSubjectBar.setMinimumSize(QtCore.QSize(0, 48))
        self.widgetSentSubjectBar.setMaximumSize(QtCore.QSize(16777215, 256))
        self.widgetSentSubjectBar.setObjectName(_fromUtf8("widgetSentSubjectBar"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widgetSentSubjectBar)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.graphicsViewSentSubjectIcon = QtGui.QGraphicsView(self.widgetSentSubjectBar)
        self.graphicsViewSentSubjectIcon.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewSentSubjectIcon.sizePolicy().hasHeightForWidth())
        self.graphicsViewSentSubjectIcon.setSizePolicy(sizePolicy)
        self.graphicsViewSentSubjectIcon.setMinimumSize(QtCore.QSize(48, 48))
        self.graphicsViewSentSubjectIcon.setMaximumSize(QtCore.QSize(48, 48))
        self.graphicsViewSentSubjectIcon.setBaseSize(QtCore.QSize(48, 48))
        self.graphicsViewSentSubjectIcon.setStyleSheet(_fromUtf8("background:rgba(0, 0, 0, 0)"))
        self.graphicsViewSentSubjectIcon.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsViewSentSubjectIcon.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewSentSubjectIcon.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewSentSubjectIcon.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewSentSubjectIcon.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewSentSubjectIcon.setForegroundBrush(brush)
        self.graphicsViewSentSubjectIcon.setSceneRect(QtCore.QRectF(0.0, 0.0, 48.0, 48.0))
        self.graphicsViewSentSubjectIcon.setObjectName(_fromUtf8("graphicsViewSentSubjectIcon"))
        self.horizontalLayout_4.addWidget(self.graphicsViewSentSubjectIcon)
        self.widget_2 = QtGui.QWidget(self.widgetSentSubjectBar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.labelSentSubjectBarSubject = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSentSubjectBarSubject.sizePolicy().hasHeightForWidth())
        self.labelSentSubjectBarSubject.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSentSubjectBarSubject.setFont(font)
        self.labelSentSubjectBarSubject.setText(_fromUtf8(""))
        self.labelSentSubjectBarSubject.setWordWrap(True)
        self.labelSentSubjectBarSubject.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelSentSubjectBarSubject.setObjectName(_fromUtf8("labelSentSubjectBarSubject"))
        self.verticalLayout_5.addWidget(self.labelSentSubjectBarSubject)
        self.labelSentSubjectBarFrom = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSentSubjectBarFrom.sizePolicy().hasHeightForWidth())
        self.labelSentSubjectBarFrom.setSizePolicy(sizePolicy)
        self.labelSentSubjectBarFrom.setText(_fromUtf8(""))
        self.labelSentSubjectBarFrom.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelSentSubjectBarFrom.setObjectName(_fromUtf8("labelSentSubjectBarFrom"))
        self.verticalLayout_5.addWidget(self.labelSentSubjectBarFrom)
        self.widget_4 = QtGui.QWidget(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.graphicsViewSentSubjectIconTo = QtGui.QGraphicsView(self.widget_4)
        self.graphicsViewSentSubjectIconTo.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsViewSentSubjectIconTo.sizePolicy().hasHeightForWidth())
        self.graphicsViewSentSubjectIconTo.setSizePolicy(sizePolicy)
        self.graphicsViewSentSubjectIconTo.setMinimumSize(QtCore.QSize(16, 16))
        self.graphicsViewSentSubjectIconTo.setMaximumSize(QtCore.QSize(16, 16))
        self.graphicsViewSentSubjectIconTo.setBaseSize(QtCore.QSize(16, 16))
        self.graphicsViewSentSubjectIconTo.setStyleSheet(_fromUtf8("background:rgba(0, 0, 0, 0)"))
        self.graphicsViewSentSubjectIconTo.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphicsViewSentSubjectIconTo.setFrameShadow(QtGui.QFrame.Plain)
        self.graphicsViewSentSubjectIconTo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewSentSubjectIconTo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewSentSubjectIconTo.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsViewSentSubjectIconTo.setForegroundBrush(brush)
        self.graphicsViewSentSubjectIconTo.setSceneRect(QtCore.QRectF(0.0, 0.0, 16.0, 16.0))
        self.graphicsViewSentSubjectIconTo.setObjectName(_fromUtf8("graphicsViewSentSubjectIconTo"))
        self.horizontalLayout_6.addWidget(self.graphicsViewSentSubjectIconTo)
        self.labelSentSubjectBarTo = QtGui.QLabel(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSentSubjectBarTo.sizePolicy().hasHeightForWidth())
        self.labelSentSubjectBarTo.setSizePolicy(sizePolicy)
        self.labelSentSubjectBarTo.setText(_fromUtf8(""))
        self.labelSentSubjectBarTo.setScaledContents(False)
        self.labelSentSubjectBarTo.setWordWrap(True)
        self.labelSentSubjectBarTo.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.labelSentSubjectBarTo.setObjectName(_fromUtf8("labelSentSubjectBarTo"))
        self.horizontalLayout_6.addWidget(self.labelSentSubjectBarTo)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.verticalLayout_6.addWidget(self.widgetSentSubjectBar)
        self.textEditSentMessage = QtGui.QTextEdit(self.widgetSentMessageView)
        self.textEditSentMessage.setReadOnly(True)
        self.textEditSentMessage.setObjectName(_fromUtf8("textEditSentMessage"))
        self.verticalLayout_6.addWidget(self.textEditSentMessage)
        self.verticalLayout.addWidget(self.splitter_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/sent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.sent, icon3, _fromUtf8(""))
        self.youridentities = QtGui.QWidget()
        self.youridentities.setObjectName(_fromUtf8("youridentities"))
        self.gridLayout_3 = QtGui.QGridLayout(self.youridentities)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButtonNewAddress = QtGui.QPushButton(self.youridentities)
        self.pushButtonNewAddress.setObjectName(_fromUtf8("pushButtonNewAddress"))
        self.gridLayout_3.addWidget(self.pushButtonNewAddress, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(689, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.tableWidgetYourIdentities = QtGui.QTableWidget(self.youridentities)
        self.tableWidgetYourIdentities.setFrameShadow(QtGui.QFrame.Sunken)
        self.tableWidgetYourIdentities.setLineWidth(1)
        self.tableWidgetYourIdentities.setAlternatingRowColors(True)
        self.tableWidgetYourIdentities.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetYourIdentities.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetYourIdentities.setObjectName(_fromUtf8("tableWidgetYourIdentities"))
        self.tableWidgetYourIdentities.setColumnCount(3)
        self.tableWidgetYourIdentities.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.tableWidgetYourIdentities.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetYourIdentities.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetYourIdentities.setHorizontalHeaderItem(2, item)
        self.tableWidgetYourIdentities.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetYourIdentities.horizontalHeader().setDefaultSectionSize(346)
        self.tableWidgetYourIdentities.horizontalHeader().setMinimumSectionSize(52)
        self.tableWidgetYourIdentities.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetYourIdentities.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetYourIdentities.verticalHeader().setVisible(False)
        self.tableWidgetYourIdentities.verticalHeader().setDefaultSectionSize(26)
        self.tableWidgetYourIdentities.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetYourIdentities.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableWidgetYourIdentities, 1, 0, 1, 2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/identities.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.youridentities, icon4, _fromUtf8(""))
        self.subscriptions = QtGui.QWidget()
        self.subscriptions.setObjectName(_fromUtf8("subscriptions"))
        self.gridLayout_4 = QtGui.QGridLayout(self.subscriptions)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tableWidgetSubscriptions = QtGui.QTableWidget(self.subscriptions)
        self.tableWidgetSubscriptions.setAlternatingRowColors(True)
        self.tableWidgetSubscriptions.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetSubscriptions.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetSubscriptions.setObjectName(_fromUtf8("tableWidgetSubscriptions"))
        self.tableWidgetSubscriptions.setColumnCount(2)
        self.tableWidgetSubscriptions.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSubscriptions.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetSubscriptions.setHorizontalHeaderItem(1, item)
        self.tableWidgetSubscriptions.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetSubscriptions.horizontalHeader().setDefaultSectionSize(400)
        self.tableWidgetSubscriptions.horizontalHeader().setHighlightSections(False)
        self.tableWidgetSubscriptions.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetSubscriptions.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetSubscriptions.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.tableWidgetSubscriptions, 2, 0, 1, 2)
        self.labelHintSubscriptions = QtGui.QLabel(self.subscriptions)
        self.labelHintSubscriptions.setEnabled(True)
        self.labelHintSubscriptions.setStyleSheet(_fromUtf8(""))
        self.labelHintSubscriptions.setWordWrap(True)
        self.labelHintSubscriptions.setObjectName(_fromUtf8("labelHintSubscriptions"))
        self.gridLayout_4.addWidget(self.labelHintSubscriptions, 0, 0, 1, 2)
        self.widgetSubscriptionsFilters = QtGui.QWidget(self.subscriptions)
        self.widgetSubscriptionsFilters.setObjectName(_fromUtf8("widgetSubscriptionsFilters"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widgetSubscriptionsFilters)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButtonAddSubscription = QtGui.QPushButton(self.widgetSubscriptionsFilters)
        self.pushButtonAddSubscription.setObjectName(_fromUtf8("pushButtonAddSubscription"))
        self.horizontalLayout_8.addWidget(self.pushButtonAddSubscription)
        self.subscriptionsSearchLineEdit = QtGui.QLineEdit(self.widgetSubscriptionsFilters)
        self.subscriptionsSearchLineEdit.setObjectName(_fromUtf8("subscriptionsSearchLineEdit"))
        self.horizontalLayout_8.addWidget(self.subscriptionsSearchLineEdit)
        self.gridLayout_4.addWidget(self.widgetSubscriptionsFilters, 1, 0, 1, 2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/subscriptions.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.subscriptions, icon5, _fromUtf8(""))
        self.addressbook = QtGui.QWidget()
        self.addressbook.setObjectName(_fromUtf8("addressbook"))
        self.gridLayout_5 = QtGui.QGridLayout(self.addressbook)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tableWidgetAddressBook = QtGui.QTableWidget(self.addressbook)
        self.tableWidgetAddressBook.setAlternatingRowColors(True)
        self.tableWidgetAddressBook.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tableWidgetAddressBook.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetAddressBook.setObjectName(_fromUtf8("tableWidgetAddressBook"))
        self.tableWidgetAddressBook.setColumnCount(2)
        self.tableWidgetAddressBook.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetAddressBook.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetAddressBook.setHorizontalHeaderItem(1, item)
        self.tableWidgetAddressBook.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetAddressBook.horizontalHeader().setDefaultSectionSize(400)
        self.tableWidgetAddressBook.horizontalHeader().setHighlightSections(False)
        self.tableWidgetAddressBook.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetAddressBook.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tableWidgetAddressBook, 2, 0, 1, 2)
        self.labelHintAddressBook = QtGui.QLabel(self.addressbook)
        self.labelHintAddressBook.setWordWrap(True)
        self.labelHintAddressBook.setObjectName(_fromUtf8("labelHintAddressBook"))
        self.gridLayout_5.addWidget(self.labelHintAddressBook, 0, 0, 1, 2)
        self.widgetAddressBookFilters = QtGui.QWidget(self.addressbook)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetAddressBookFilters.sizePolicy().hasHeightForWidth())
        self.widgetAddressBookFilters.setSizePolicy(sizePolicy)
        self.widgetAddressBookFilters.setObjectName(_fromUtf8("widgetAddressBookFilters"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widgetAddressBookFilters)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButtonAddAddressBook = QtGui.QPushButton(self.widgetAddressBookFilters)
        self.pushButtonAddAddressBook.setObjectName(_fromUtf8("pushButtonAddAddressBook"))
        self.horizontalLayout_7.addWidget(self.pushButtonAddAddressBook)
        self.addressBookSearchLineEdit = QtGui.QLineEdit(self.widgetAddressBookFilters)
        self.addressBookSearchLineEdit.setObjectName(_fromUtf8("addressBookSearchLineEdit"))
        self.horizontalLayout_7.addWidget(self.addressBookSearchLineEdit)
        self.gridLayout_5.addWidget(self.widgetAddressBookFilters, 1, 0, 1, 2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/addressbook.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.addressbook, icon6, _fromUtf8(""))
        self.blackwhitelist = QtGui.QWidget()
        self.blackwhitelist.setObjectName(_fromUtf8("blackwhitelist"))
        self.gridLayout_6 = QtGui.QGridLayout(self.blackwhitelist)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tableWidgetBlacklist = QtGui.QTableWidget(self.blackwhitelist)
        self.tableWidgetBlacklist.setAlternatingRowColors(True)
        self.tableWidgetBlacklist.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetBlacklist.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetBlacklist.setObjectName(_fromUtf8("tableWidgetBlacklist"))
        self.tableWidgetBlacklist.setColumnCount(2)
        self.tableWidgetBlacklist.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBlacklist.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetBlacklist.setHorizontalHeaderItem(1, item)
        self.tableWidgetBlacklist.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetBlacklist.horizontalHeader().setDefaultSectionSize(400)
        self.tableWidgetBlacklist.horizontalHeader().setHighlightSections(False)
        self.tableWidgetBlacklist.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetBlacklist.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetBlacklist.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.tableWidgetBlacklist, 1, 0, 1, 2)
        self.widget_5 = QtGui.QWidget(self.blackwhitelist)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButtonAddBlacklist = QtGui.QPushButton(self.widget_5)
        self.pushButtonAddBlacklist.setObjectName(_fromUtf8("pushButtonAddBlacklist"))
        self.horizontalLayout_9.addWidget(self.pushButtonAddBlacklist)
        self.comboBlacklist = QtGui.QComboBox(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBlacklist.sizePolicy().hasHeightForWidth())
        self.comboBlacklist.setSizePolicy(sizePolicy)
        self.comboBlacklist.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBlacklist.setObjectName(_fromUtf8("comboBlacklist"))
        self.comboBlacklist.addItem(_fromUtf8(""))
        self.comboBlacklist.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.comboBlacklist)
        self.lineEdit = QtGui.QLineEdit(self.widget_5)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_9.addWidget(self.lineEdit)
        self.gridLayout_6.addWidget(self.widget_5, 0, 0, 1, 2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/blacklist.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.blackwhitelist, icon7, _fromUtf8(""))
        self.networkstatus = QtGui.QWidget()
        self.networkstatus.setObjectName(_fromUtf8("networkstatus"))
        self.pushButtonStatusIcon = QtGui.QPushButton(self.networkstatus)
        self.pushButtonStatusIcon.setGeometry(QtCore.QRect(680, 440, 21, 23))
        self.pushButtonStatusIcon.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/redicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStatusIcon.setIcon(icon8)
        self.pushButtonStatusIcon.setFlat(True)
        self.pushButtonStatusIcon.setObjectName(_fromUtf8("pushButtonStatusIcon"))
        self.tableWidgetConnectionCount = QtGui.QTableWidget(self.networkstatus)
        self.tableWidgetConnectionCount.setGeometry(QtCore.QRect(20, 70, 241, 241))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.tableWidgetConnectionCount.setPalette(palette)
        self.tableWidgetConnectionCount.setFrameShape(QtGui.QFrame.Box)
        self.tableWidgetConnectionCount.setFrameShadow(QtGui.QFrame.Plain)
        self.tableWidgetConnectionCount.setProperty("showDropIndicator", False)
        self.tableWidgetConnectionCount.setAlternatingRowColors(True)
        self.tableWidgetConnectionCount.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tableWidgetConnectionCount.setObjectName(_fromUtf8("tableWidgetConnectionCount"))
        self.tableWidgetConnectionCount.setColumnCount(2)
        self.tableWidgetConnectionCount.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetConnectionCount.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetConnectionCount.setHorizontalHeaderItem(1, item)
        self.tableWidgetConnectionCount.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetConnectionCount.horizontalHeader().setHighlightSections(False)
        self.tableWidgetConnectionCount.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetConnectionCount.verticalHeader().setVisible(False)
        self.labelTotalConnections = QtGui.QLabel(self.networkstatus)
        self.labelTotalConnections.setGeometry(QtCore.QRect(20, 30, 401, 16))
        self.labelTotalConnections.setObjectName(_fromUtf8("labelTotalConnections"))
        self.labelStartupTime = QtGui.QLabel(self.networkstatus)
        self.labelStartupTime.setGeometry(QtCore.QRect(320, 110, 331, 20))
        self.labelStartupTime.setObjectName(_fromUtf8("labelStartupTime"))
        self.labelMessageCount = QtGui.QLabel(self.networkstatus)
        self.labelMessageCount.setGeometry(QtCore.QRect(350, 130, 361, 16))
        self.labelMessageCount.setObjectName(_fromUtf8("labelMessageCount"))
        self.labelPubkeyCount = QtGui.QLabel(self.networkstatus)
        self.labelPubkeyCount.setGeometry(QtCore.QRect(350, 170, 331, 16))
        self.labelPubkeyCount.setObjectName(_fromUtf8("labelPubkeyCount"))
        self.labelBroadcastCount = QtGui.QLabel(self.networkstatus)
        self.labelBroadcastCount.setGeometry(QtCore.QRect(350, 150, 351, 16))
        self.labelBroadcastCount.setObjectName(_fromUtf8("labelBroadcastCount"))
        self.labelLookupsPerSecond = QtGui.QLabel(self.networkstatus)
        self.labelLookupsPerSecond.setGeometry(QtCore.QRect(320, 250, 291, 16))
        self.labelLookupsPerSecond.setObjectName(_fromUtf8("labelLookupsPerSecond"))
        self.labelBytesRecvCount = QtGui.QLabel(self.networkstatus)
        self.labelBytesRecvCount.setGeometry(QtCore.QRect(350, 210, 251, 16))
        self.labelBytesRecvCount.setObjectName(_fromUtf8("labelBytesRecvCount"))
        self.labelBytesSentCount = QtGui.QLabel(self.networkstatus)
        self.labelBytesSentCount.setGeometry(QtCore.QRect(350, 230, 251, 16))
        self.labelBytesSentCount.setObjectName(_fromUtf8("labelBytesSentCount"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/images/networkstatus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.networkstatus, icon9, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuNew = QtGui.QMenu(self.menuFile)
        self.menuNew.setObjectName(_fromUtf8("menuNew"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuViewTabPosition = QtGui.QMenu(self.menuView)
        self.menuViewTabPosition.setObjectName(_fromUtf8("menuViewTabPosition"))
        self.actionViewToggleInbox = QtGui.QMenu(self.menuView)
        self.actionViewToggleInbox.setObjectName(_fromUtf8("actionViewToggleInbox"))
        self.actionViewToggleSent = QtGui.QMenu(self.menuView)
        self.actionViewToggleSent.setObjectName(_fromUtf8("actionViewToggleSent"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_keys = QtGui.QAction(MainWindow)
        self.actionImport_keys.setObjectName(_fromUtf8("actionImport_keys"))
        self.actionManageKeys = QtGui.QAction(MainWindow)
        self.actionManageKeys.setCheckable(False)
        self.actionManageKeys.setEnabled(True)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("dialog-password"))
        self.actionManageKeys.setIcon(icon)
        self.actionManageKeys.setObjectName(_fromUtf8("actionManageKeys"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-contents"))
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-about"))
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSettings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-properties"))
        self.actionSettings.setIcon(icon)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionRegenerateDeterministicAddresses = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-refresh"))
        self.actionRegenerateDeterministicAddresses.setIcon(icon)
        self.actionRegenerateDeterministicAddresses.setObjectName(_fromUtf8("actionRegenerateDeterministicAddresses"))
        self.actionDeleteAllTrashedMessages = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("user-trash"))
        self.actionDeleteAllTrashedMessages.setIcon(icon)
        self.actionDeleteAllTrashedMessages.setObjectName(_fromUtf8("actionDeleteAllTrashedMessages"))
        self.actionJoinChan = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("contact-new"))
        self.actionJoinChan.setIcon(icon)
        self.actionJoinChan.setObjectName(_fromUtf8("actionJoinChan"))
        self.actionViewToggleLayout = QtGui.QAction(MainWindow)
        self.actionViewToggleLayout.setCheckable(False)
        self.actionViewToggleLayout.setChecked(False)
        self.actionViewToggleLayout.setStatusTip(_fromUtf8(""))
        self.actionViewToggleLayout.setObjectName(_fromUtf8("actionViewToggleLayout"))
        self.actionViewToggleFilters = QtGui.QAction(MainWindow)
        self.actionViewToggleFilters.setCheckable(True)
        self.actionViewToggleFilters.setChecked(False)
        self.actionViewToggleFilters.setStatusTip(_fromUtf8(""))
        self.actionViewToggleFilters.setObjectName(_fromUtf8("actionViewToggleFilters"))
        self.actionViewToggleStatusBar = QtGui.QAction(MainWindow)
        self.actionViewToggleStatusBar.setCheckable(True)
        self.actionViewToggleStatusBar.setStatusTip(_fromUtf8(""))
        self.actionViewToggleStatusBar.setObjectName(_fromUtf8("actionViewToggleStatusBar"))
        self.actionViewToggleTabs = QtGui.QAction(MainWindow)
        self.actionViewToggleTabs.setObjectName(_fromUtf8("actionViewToggleTabs"))
        self.actionViewTabPositionNorth = QtGui.QAction(MainWindow)
        self.actionViewTabPositionNorth.setCheckable(True)
        self.actionViewTabPositionNorth.setObjectName(_fromUtf8("actionViewTabPositionNorth"))
        self.actionViewTabPositionSouth = QtGui.QAction(MainWindow)
        self.actionViewTabPositionSouth.setCheckable(True)
        self.actionViewTabPositionSouth.setObjectName(_fromUtf8("actionViewTabPositionSouth"))
        self.actionViewTabPositionEast = QtGui.QAction(MainWindow)
        self.actionViewTabPositionEast.setCheckable(True)
        self.actionViewTabPositionEast.setObjectName(_fromUtf8("actionViewTabPositionEast"))
        self.actionViewTabPositionWest = QtGui.QAction(MainWindow)
        self.actionViewTabPositionWest.setCheckable(True)
        self.actionViewTabPositionWest.setObjectName(_fromUtf8("actionViewTabPositionWest"))
        self.actionNewMessage = QtGui.QAction(MainWindow)
        self.actionNewMessage.setObjectName(_fromUtf8("actionNewMessage"))
        self.actionNewIdentity = QtGui.QAction(MainWindow)
        self.actionNewIdentity.setObjectName(_fromUtf8("actionNewIdentity"))
        self.actionNewAddressBook = QtGui.QAction(MainWindow)
        self.actionNewAddressBook.setObjectName(_fromUtf8("actionNewAddressBook"))
        self.actionNewSubscription = QtGui.QAction(MainWindow)
        self.actionNewSubscription.setObjectName(_fromUtf8("actionNewSubscription"))
        self.actionNewBlackWhiteList = QtGui.QAction(MainWindow)
        self.actionNewBlackWhiteList.setObjectName(_fromUtf8("actionNewBlackWhiteList"))
        self.actionViewToggleHints = QtGui.QAction(MainWindow)
        self.actionViewToggleHints.setCheckable(True)
        self.actionViewToggleHints.setStatusTip(_fromUtf8(""))
        self.actionViewToggleHints.setObjectName(_fromUtf8("actionViewToggleHints"))
        self.actionViewToggleSubjectBar = QtGui.QAction(MainWindow)
        self.actionViewToggleSubjectBar.setCheckable(True)
        self.actionViewToggleSubjectBar.setStatusTip(_fromUtf8(""))
        self.actionViewToggleSubjectBar.setObjectName(_fromUtf8("actionViewToggleSubjectBar"))
        self.actionViewToggleTabLabels = QtGui.QAction(MainWindow)
        self.actionViewToggleTabLabels.setCheckable(True)
        self.actionViewToggleTabLabels.setStatusTip(_fromUtf8(""))
        self.actionViewToggleTabLabels.setObjectName(_fromUtf8("actionViewToggleTabLabels"))
        self.actionViewToggleInboxTo = QtGui.QAction(MainWindow)
        self.actionViewToggleInboxTo.setCheckable(True)
        self.actionViewToggleInboxTo.setStatusTip(_fromUtf8(""))
        self.actionViewToggleInboxTo.setObjectName(_fromUtf8("actionViewToggleInboxTo"))
        self.actionViewToggleInboxFrom = QtGui.QAction(MainWindow)
        self.actionViewToggleInboxFrom.setCheckable(True)
        self.actionViewToggleInboxFrom.setStatusTip(_fromUtf8(""))
        self.actionViewToggleInboxFrom.setObjectName(_fromUtf8("actionViewToggleInboxFrom"))
        self.actionViewToggleInboxReceived = QtGui.QAction(MainWindow)
        self.actionViewToggleInboxReceived.setCheckable(True)
        self.actionViewToggleInboxReceived.setStatusTip(_fromUtf8(""))
        self.actionViewToggleInboxReceived.setObjectName(_fromUtf8("actionViewToggleInboxReceived"))
        self.actionViewToggleSentTo = QtGui.QAction(MainWindow)
        self.actionViewToggleSentTo.setCheckable(True)
        self.actionViewToggleSentTo.setObjectName(_fromUtf8("actionViewToggleSentTo"))
        self.actionViewToggleSentFrom = QtGui.QAction(MainWindow)
        self.actionViewToggleSentFrom.setCheckable(True)
        self.actionViewToggleSentFrom.setObjectName(_fromUtf8("actionViewToggleSentFrom"))
        self.actionViewToggleSentStatus = QtGui.QAction(MainWindow)
        self.actionViewToggleSentStatus.setCheckable(True)
        self.actionViewToggleSentStatus.setObjectName(_fromUtf8("actionViewToggleSentStatus"))
        self.menuNew.addAction(self.actionJoinChan)
        self.menuNew.addAction(self.actionNewMessage)
        self.menuNew.addAction(self.actionNewIdentity)
        self.menuNew.addAction(self.actionNewAddressBook)
        self.menuNew.addAction(self.actionNewSubscription)
        self.menuNew.addAction(self.actionNewBlackWhiteList)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuViewTabPosition.addAction(self.actionViewTabPositionNorth)
        self.menuViewTabPosition.addAction(self.actionViewTabPositionEast)
        self.menuViewTabPosition.addAction(self.actionViewTabPositionSouth)
        self.menuViewTabPosition.addAction(self.actionViewTabPositionWest)
        self.actionViewToggleInbox.addAction(self.actionViewToggleInboxTo)
        self.actionViewToggleInbox.addAction(self.actionViewToggleInboxFrom)
        self.actionViewToggleInbox.addAction(self.actionViewToggleInboxReceived)
        self.actionViewToggleSent.addAction(self.actionViewToggleSentTo)
        self.actionViewToggleSent.addAction(self.actionViewToggleSentFrom)
        self.actionViewToggleSent.addAction(self.actionViewToggleSentStatus)
        self.menuView.addAction(self.actionViewToggleLayout)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionViewToggleTabLabels)
        self.menuView.addAction(self.actionViewToggleFilters)
        self.menuView.addAction(self.actionViewToggleSubjectBar)
        self.menuView.addAction(self.actionViewToggleStatusBar)
        self.menuView.addAction(self.actionViewToggleHints)
        self.menuView.addAction(self.actionViewToggleInbox.menuAction())
        self.menuView.addAction(self.actionViewToggleSent.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuViewTabPosition.menuAction())
        self.menuTools.addAction(self.actionDeleteAllTrashedMessages)
        self.menuTools.addAction(self.actionRegenerateDeterministicAddresses)
        self.menuTools.addAction(self.actionManageKeys)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.radioButtonSpecific, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.labelSendBroadcastWarning.hide)
        QtCore.QObject.connect(self.radioButtonBroadcast, QtCore.SIGNAL(_fromUtf8("clicked()")), self.labelSendBroadcastWarning.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.tableWidgetInbox)
        MainWindow.setTabOrder(self.tableWidgetInbox, self.radioButtonSpecific)
        MainWindow.setTabOrder(self.radioButtonSpecific, self.radioButtonBroadcast)
        MainWindow.setTabOrder(self.radioButtonBroadcast, self.comboBoxSendFrom)
        MainWindow.setTabOrder(self.comboBoxSendFrom, self.pushButtonLoadFromAddressBook)
        MainWindow.setTabOrder(self.pushButtonLoadFromAddressBook, self.lineEditSubject)
        MainWindow.setTabOrder(self.lineEditSubject, self.textEditMessage)
        MainWindow.setTabOrder(self.textEditMessage, self.pushButtonSend)
        MainWindow.setTabOrder(self.pushButtonSend, self.tableWidgetSent)
        MainWindow.setTabOrder(self.tableWidgetSent, self.pushButtonNewAddress)
        MainWindow.setTabOrder(self.pushButtonNewAddress, self.tableWidgetYourIdentities)
        MainWindow.setTabOrder(self.tableWidgetYourIdentities, self.tableWidgetSubscriptions)
        MainWindow.setTabOrder(self.tableWidgetSubscriptions, self.tableWidgetAddressBook)
        MainWindow.setTabOrder(self.tableWidgetAddressBook, self.tableWidgetBlacklist)
        MainWindow.setTabOrder(self.tableWidgetBlacklist, self.tableWidgetConnectionCount)
        MainWindow.setTabOrder(self.tableWidgetConnectionCount, self.pushButtonStatusIcon)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Bitmessage", None))
        self.inbox.setToolTip(_translate("MainWindow", "Inbox", None))
        self.inboxSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.inboxSearchOptionCB.setItemText(0, _translate("MainWindow", "All", None))
        self.inboxSearchOptionCB.setItemText(1, _translate("MainWindow", "To", None))
        self.inboxSearchOptionCB.setItemText(2, _translate("MainWindow", "From", None))
        self.inboxSearchOptionCB.setItemText(3, _translate("MainWindow", "Subject", None))
        self.inboxSearchOptionCB.setItemText(4, _translate("MainWindow", "Message", None))
        self.splitter.setToolTip(_translate("MainWindow", "<span style=\"display:none\"></span>", None))
        self.tableWidgetInbox.setSortingEnabled(True)
        item = self.tableWidgetInbox.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "To", None))
        item = self.tableWidgetInbox.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "From", None))
        item = self.tableWidgetInbox.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.tableWidgetInbox.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Received", None))
        self.labelInboxSubjectBarFrom.setToolTip(_translate("MainWindow", "From Address", None))
        self.widget_3.setToolTip(_translate("MainWindow", "To Address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inbox), _translate("MainWindow", "Inbox", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.inbox), _translate("MainWindow", "Inbox", None))
        self.send.setToolTip(_translate("MainWindow", "Compose", None))
        self.pushButtonLoadFromAddressBook.setText(_translate("MainWindow", "Load from Address book", None))
        self.pushButtonFetchNamecoinID.setText(_translate("MainWindow", "Fetch Namecoin ID", None))
        self.label_4.setText(_translate("MainWindow", "Message:", None))
        self.label_3.setText(_translate("MainWindow", "Subject:", None))
        self.radioButtonSpecific.setText(_translate("MainWindow", "Send to one or more specific people", None))
        self.label.setText(_translate("MainWindow", "To:", None))
        self.label_2.setText(_translate("MainWindow", "From:", None))
        self.textEditMessage.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Open Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>", None))
        self.radioButtonBroadcast.setText(_translate("MainWindow", "Broadcast to everyone who is subscribed to your address", None))
        self.pushButtonSend.setText(_translate("MainWindow", "Send", None))
        self.labelSendBroadcastWarning.setText(_translate("MainWindow", "Be aware that broadcasts are only encrypted with your address. Anyone who knows your address can read them.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.send), _translate("MainWindow", "Compose", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.send), _translate("MainWindow", "Compose", None))
        self.sent.setToolTip(_translate("MainWindow", "Sent", None))
        self.sentSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.sentSearchOptionCB.setItemText(0, _translate("MainWindow", "All", None))
        self.sentSearchOptionCB.setItemText(1, _translate("MainWindow", "To", None))
        self.sentSearchOptionCB.setItemText(2, _translate("MainWindow", "From", None))
        self.sentSearchOptionCB.setItemText(3, _translate("MainWindow", "Subject", None))
        self.sentSearchOptionCB.setItemText(4, _translate("MainWindow", "Message", None))
        self.tableWidgetSent.setSortingEnabled(True)
        item = self.tableWidgetSent.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "To", None))
        item = self.tableWidgetSent.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "From", None))
        item = self.tableWidgetSent.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.tableWidgetSent.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status", None))
        self.widget_4.setToolTip(_translate("MainWindow", "To Address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sent), _translate("MainWindow", "Sent", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.sent), _translate("MainWindow", "Sent", None))
        self.youridentities.setToolTip(_translate("MainWindow", "Identities", None))
        self.pushButtonNewAddress.setText(_translate("MainWindow", "New", None))
        self.tableWidgetYourIdentities.setSortingEnabled(True)
        item = self.tableWidgetYourIdentities.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Label (not shown to anyone)", None))
        item = self.tableWidgetYourIdentities.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        item = self.tableWidgetYourIdentities.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stream", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.youridentities), _translate("MainWindow", "Identities", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.youridentities), _translate("MainWindow", "Identities", None))
        self.subscriptions.setToolTip(_translate("MainWindow", "Subscriptions", None))
        self.tableWidgetSubscriptions.setSortingEnabled(True)
        item = self.tableWidgetSubscriptions.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Label", None))
        item = self.tableWidgetSubscriptions.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        self.labelHintSubscriptions.setText(_translate("MainWindow", "Here you can subscribe to \'broadcast messages\' that are sent by other users. Messages will appear in your Inbox. Addresses here override those on the Blacklist tab.", None))
        self.pushButtonAddSubscription.setText(_translate("MainWindow", "New", None))
        self.subscriptionsSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.subscriptions), _translate("MainWindow", "Subscriptions", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.subscriptions), _translate("MainWindow", "Subscriptions", None))
        self.addressbook.setToolTip(_translate("MainWindow", "Address Book", None))
        self.tableWidgetAddressBook.setSortingEnabled(True)
        item = self.tableWidgetAddressBook.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name or Label", None))
        item = self.tableWidgetAddressBook.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        self.labelHintAddressBook.setText(_translate("MainWindow", "The Address book is useful for adding names or labels to other people\'s Bitmessage addresses so that you can recognize them more easily in your inbox. You can add entries here using the \'Add\' button, or from your inbox by right-clicking on a message.", None))
        self.pushButtonAddAddressBook.setText(_translate("MainWindow", "New", None))
        self.addressBookSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addressbook), _translate("MainWindow", "Address Book", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.addressbook), _translate("MainWindow", "Address Book", None))
        self.blackwhitelist.setToolTip(_translate("MainWindow", "Blacklist", None))
        self.tableWidgetBlacklist.setSortingEnabled(True)
        item = self.tableWidgetBlacklist.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name or Label", None))
        item = self.tableWidgetBlacklist.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        self.pushButtonAddBlacklist.setText(_translate("MainWindow", "New", None))
        self.comboBlacklist.setToolTip(_translate("MainWindow", "Allow all incoming messages except for those on the Blacklist", None))
        self.comboBlacklist.setItemText(0, _translate("MainWindow", "Use a Blacklist", None))
        self.comboBlacklist.setItemText(1, _translate("MainWindow", "Use a Whitelist", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blackwhitelist), _translate("MainWindow", "Blacklist", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.blackwhitelist), _translate("MainWindow", "Blacklist", None))
        self.networkstatus.setToolTip(_translate("MainWindow", "Network", None))
        item = self.tableWidgetConnectionCount.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stream #", None))
        item = self.tableWidgetConnectionCount.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Connections", None))
        self.labelTotalConnections.setText(_translate("MainWindow", "Total connections: 0", None))
        self.labelStartupTime.setText(_translate("MainWindow", "Since startup at asdf:", None))
        self.labelMessageCount.setText(_translate("MainWindow", "Processed 0 person-to-person message.", None))
        self.labelPubkeyCount.setText(_translate("MainWindow", "Processed 0 public key.", None))
        self.labelBroadcastCount.setText(_translate("MainWindow", "Processed 0 broadcast.", None))
        self.labelLookupsPerSecond.setText(_translate("MainWindow", "Inventory lookups per second: 0", None))
        self.labelBytesRecvCount.setText(_translate("MainWindow", "Down: 0 KB/s", None))
        self.labelBytesSentCount.setText(_translate("MainWindow", "Up: 0 KB/s", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.networkstatus), _translate("MainWindow", "Network", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.networkstatus), _translate("MainWindow", "Network", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuNew.setTitle(_translate("MainWindow", "New", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuViewTabPosition.setTitle(_translate("MainWindow", "Tab Position", None))
        self.actionViewToggleInbox.setTitle(_translate("MainWindow", "Inbox Columns", None))
        self.actionViewToggleSent.setTitle(_translate("MainWindow", "Sent Columns", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.actionImport_keys.setText(_translate("MainWindow", "Import keys", None))
        self.actionManageKeys.setText(_translate("MainWindow", "Manage keys", None))
        self.actionExit.setText(_translate("MainWindow", "Quit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionRegenerateDeterministicAddresses.setText(_translate("MainWindow", "Regenerate deterministic addresses", None))
        self.actionDeleteAllTrashedMessages.setText(_translate("MainWindow", "Delete all trashed messages", None))
        self.actionJoinChan.setText(_translate("MainWindow", "Chan", None))
        self.actionJoinChan.setToolTip(_translate("MainWindow", "Join / Create chan", None))
        self.actionViewToggleLayout.setText(_translate("MainWindow", "Toggle Layout", None))
        self.actionViewToggleFilters.setText(_translate("MainWindow", "Show Filters", None))
        self.actionViewToggleStatusBar.setText(_translate("MainWindow", "Show Status Bar", None))
        self.actionViewToggleTabs.setText(_translate("MainWindow", "Tabs", None))
        self.actionViewTabPositionNorth.setText(_translate("MainWindow", "North", None))
        self.actionViewTabPositionSouth.setText(_translate("MainWindow", "South", None))
        self.actionViewTabPositionEast.setText(_translate("MainWindow", "East", None))
        self.actionViewTabPositionWest.setText(_translate("MainWindow", "West", None))
        self.actionNewMessage.setText(_translate("MainWindow", "Message", None))
        self.actionNewIdentity.setText(_translate("MainWindow", "Identity", None))
        self.actionNewAddressBook.setText(_translate("MainWindow", "Address book", None))
        self.actionNewSubscription.setText(_translate("MainWindow", "Subscription", None))
        self.actionNewBlackWhiteList.setText(_translate("MainWindow", "Blacklist", None))
        self.actionViewToggleHints.setText(_translate("MainWindow", "Show Hints", None))
        self.actionViewToggleSubjectBar.setText(_translate("MainWindow", "Show Subject Bar", None))
        self.actionViewToggleTabLabels.setText(_translate("MainWindow", "Show Tab Labels", None))
        self.actionViewToggleInboxTo.setText(_translate("MainWindow", "To", None))
        self.actionViewToggleInboxFrom.setText(_translate("MainWindow", "From", None))
        self.actionViewToggleInboxReceived.setText(_translate("MainWindow", "Received", None))
        self.actionViewToggleSentTo.setText(_translate("MainWindow", "To", None))
        self.actionViewToggleSentFrom.setText(_translate("MainWindow", "From", None))
        self.actionViewToggleSentStatus.setText(_translate("MainWindow", "Status", None))

import bitmessage_icons_rc
